import { test, expect } from "@playwright/test";
test.beforeEach(async ({ page }) => { await page.addInitScript(() => sessionStorage.setItem("pagokiosco.install-dismissed", "1")); });
test("inventario, venta, importe libre y cierre persisten", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Nuevo producto" }).click();
  await page.getByLabel("Nombre", { exact: true }).fill("Alfajor de chocolate");
  await page.getByLabel("Costo ($)", { exact: true }).fill("1000");
  await expect(page.getByLabel("Precio de venta ($)")).toHaveValue("1400");
  await page.getByLabel("Stock inicial").fill("5");
  await page.getByRole("button", { name: "Guardar producto" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: /SIN CÓDIGO Alfajor/ }).click();
  await page.screenshot({ path: `test-results/pos-${testInfo.project.name}.png`, fullPage: true });
  await page.getByRole("button", { name: "Registrar venta" }).click();
  await page.getByRole("button", { name: "Confirmar y descontar stock" }).click();
  await expect(page.locator(".success")).toContainText("Venta registrada");
  await page.getByRole("button", { name: "Agregar importe libre" }).click();
  await page.getByLabel("Importe ($)").fill("250");
  await page.getByRole("button", { name: "Agregar al carrito" }).click();
  await page.getByRole("button", { name: "Registrar venta" }).click();
  await page.getByRole("button", { name: "Transferencia", exact: true }).click();
  await page.getByRole("button", { name: "Confirmar y descontar stock" }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.reload();
  await page.getByRole("button", { name: "Inventario" }).click();
  await expect(page.locator(".product-row")).toContainText("4 u.");
  await page.getByRole("button", { name: "Caja", exact: false }).click();
  await page.getByRole("button", { name: "Cierre de caja", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("1.650");
  await expect(page.getByRole("dialog")).toContainText("2 ventas registradas");
  await page.getByRole("button", { name: "Listo", exact: true }).click();
  await page.getByRole("combobox").selectOption("365");
  await expect(page.locator(".metrics-summary")).toContainText("1.650");
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
});
test("consulta sin red permite alta manual y cerrar el diálogo", async ({ page }) => {
  await page.route("**/api/products?*", route => route.abort());
  await page.goto("/");
  await page.getByRole("button", { name: "Escanear", exact: false }).click();
  await page.getByLabel("Código EAN", { exact: true }).fill("7791234567898");
  await page.getByRole("button", { name: "Buscar código" }).click();
  await page.getByRole("button", { name: "Cargar producto manualmente" }).click();
  await expect(page.getByLabel("Código de barras")).toHaveValue("7791234567898");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
});
